on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node

      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4.0.0
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.ABOVIQ_NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
